### PR TITLE
Swift3

### PR DESCRIPTION
**Pull request by george-gw**

### CODE REVIEW

**Comment by attheodo** [comment]
@george-gw thanks for all the good work over here.

Did you have time to run/convert the tests in Swift 3 as well? Also I think `-pre` needs to be `--pre` for proper beta cocoapods installation in Travis.

Let's fix them and then merge to master and push to the trunk. I've kept a swift2.2 compatible branch in case anyone needs it.

**Comment by george-gw** [comment]
@attheodo All tests ran successfully with the switch to swift3, I just fixed the typo, good catch :)

**Comment by attheodo** [comment]
Great work @george-gw !

**Comment by attheodo** [comment]
Btw @george-gw is this component used by any of your apps live in the App Store? I am thinking we could create a section in `README` with a list of the apps using this in production. Let me know if you're willing to share your app's name and URL so I can update accordingly.

**Comment by george-gw** [comment]
Thanks, HTH :)

Good idea @attheodo.
I'm currently using this library, for development purposes, in a version of an app that's still under development, unsure if we'll have some component that will use it in production yet.

**Pull request merged**
